micronaut:
  hellomessage: Hi there!
  server:
    port: 8081
  application:
    name: conference-service-micronaut
  metrics:
    enabled: true
app:
  hellomessage: Hi there!
#  io:
#    watch:
#      paths: src/main
#      restart: true

country:
  service:
    url: http://localhost:9000

endpoints:
  all:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''    
jpa:
  default:
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update

